# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

env:
  global:
    # TRAVIS_API_TOKEN
    - secure: "FbwTA/8mFFlonrxiSTICou5nw8gylFve/TArnHdKtcaC5Fub+o2Y4FFpESWeT/8ub4qzfzOCZZbaffmcLXrqqzSnAjZH4g/0qRwxbD/8MZ+ybY7DLg+mLyG9WtztJd2mXO17askqguE0jf2c2lJe/TPFdlnErqx3G6rBDaOkTgUJYGkviiMTsBgpi2XmmU1qgx40V+zzBy+66lfMeh/KGybtOT5JtmMXk9gn7MGHXyGujQad1dRE/3T4OjeoMcDFflnMecVItAallPpDwKPQRovsPehOrrdajczoWolh2vwwWJqCH1m8Ciw8+eRq5R1o6PPlzYXDgcx7WyNBX9qbzJdiWEIfipJJPkRjezBofjbOhH/2wWmG83B/G9YNN9n5EWhd1x6Us4sHZngw69jLw5PAnMmcCJ1gU2dMbsbCzSZhfeNJ3U/UOMnGKEP6HrqbOl4JIVLBiXG8J4Rv3E8R4RtHOjBKRJwo4JWmQBTtTrTtNUr27P+fbb63k4ivUdQVz47LxJVcll4xxCLYCtC4Tt8k+PyqQDvcH5FbJ+auDn33E9+IDcnzMZfryjY9BA9ZL2dTvrhE1eEQOsViYz1IX5sb1OMr0syKHdvJ+9LUc5zPu/gvWod+waGfNUvNDT5a3v9bX8g1zN75KXMqyES7r8IFAA7tQYUZQoMxVPXvoac="

language: node_js

matrix:
  include:

    # 1. Build used for checking links and, if needed,
    #    to trigger a rebuild of the site.

    - os: linux
      dist: trusty
      install:
        - gem install awesome_bot
      node_js:
        - node
      script:
        - ./.travis/check-links.sh && ./.travis/trigger-site-update.sh

    # 2. Build used for running the tests for sonar on Ubuntu.

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
            - ubuntu-toolchain-r-test
          packages:
            - google-chrome-stable
            - libcairo2-dev
            - libjpeg8-dev
            - libpango1.0-dev
            - libgif-dev
            - g++-4.9
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      env:
        - CXX=g++-4.9
      node_js:
        - node
      script:
        - npm run test-on-travis

    # 3. Build used for running the tests for sonar on macOS.

    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew install pkg-config cairo libpng jpeg giflib
        - brew cask install google-chrome
      node_js:
        - node
      script:
        - npm run test-on-travis

notifications:
  email:
    on_failure: always
    on_success: never
