# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

language: node_js

matrix:
  include:

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
        - gem install awesome_bot
      node_js:
        - node

    - os: osx
      before_install:
        - brew cask install google-chrome
        - gem install awesome_bot
      node_js:
        - node

notifications:
  email:
    on_failure: always
    on_success: never

script:

  # Run tests.
  - npm test

  # Check for broken links.
  - |
      find . -name "*.md" \
              -not -path "./node_modules/*" \
              -not -path "./dist/*" \
              -not -path "./coverage/*" \
      | xargs awesome_bot \
              --allow-dupe \
              --allow-redirect \
              --set-timeout 150
