# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
jobs:
- template: azure-pipelines/workers.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu 16.04'

- template: azure-pipelines/workers.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'

- template: azure-pipelines/workers.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
