# Dependabot PRs
# Run only latest version of node on Linux
jobs:
  - template: latest-version.yml
    parameters:
        name: Linux_Dependabot
        vmImage: 'ubuntu 16.04'
        condition: and(eq(variables['Build.Reason'], 'PullRequest'), startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/dependabot/'))
