steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Update Chrome on Linux'
  - script: brew update && brew cask install google-chrome
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: 'Update Chrome on macOS'
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: 'Use Yarn 1.x'
    inputs:
      checkLatest: true
  - script: yarn
    displayName: 'Install dependencies'
  - script: yarn test
    displayName: 'Test'
  # The only assets that will be stored for faster "build times" are
  # the ones generated:
  # * on Linux with the latest node version
  # * from the master branch
  # * each time that we merge something (not scheduled)
  #
  # Otherwise we will be rewritting the file multiple times as the
  # hash of the commit is used for the zip name (hash.zip)
  - script: ./scripts/dist-management/pack-and-upload.sh
    condition: >
      and(
        eq(variables['Agent.OS'], 'Linux'),
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        not(eq(variables['Build.Reason'], 'Schedule')),
        eq(variables['node_version'], '12.x')
      )
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    displayName: 'Publish resources'
